### ISSUE TITLE
Deprecation warning with Ember 2.18

### ISSUE THREAD

**Issue by bungeye** [smile-io/ember-cli-stripe#32]
Please update babel dependency as using ember-cli-babel@5.2.4 installs ember-cli-version-checker@1.3.1 which causes deprecation warning as per:

[https://github.com/ember-cli/ember-cli-version-checker/issues/48#issuecomment-354912902](https://github.com/ember-cli/ember-cli-version-checker/issues/48#issuecomment-354912902)

**Comment by oskarrough** [comment]
Another deprecation is `ember-invoke-action`. See https://github.com/miguelcobain/ember-leaflet/issues/188

**Comment by vladucu** [comment]
will look into fixing left deprecations next couple of days, thx

**Comment by oskarrough** [comment]
@vladucu I tried using the master branch in our app and it seems all deprecations are gone 👏 Maybe we can have a new release with the fixes?

**Comment by vladucu** [comment]
@oskarrough done

**Comment by vladucu** [comment]
this should be fixed with `2.0`
