### ISSUE TITLE
Is 3D Secure supported?

### ISSUE THREAD

**Issue by caltabid** [smile-io/ember-cli-stripe#33]

**Comment by vladucu** [comment]
hey,

this is just a wrapper for the [Stripe Checkout](https://stripe.com/docs/checkout) lib, which I don't think supports it, at least at this point.

For 3D secure, maybe take a look at [ember-stripe-elements](https://github.com/code-corps/ember-stripe-elements) and check the [Stripe guide](https://stripe.com/docs/sources/three-d-secure)
