### ISSUE TITLE
Cannot read property 'getAttribute' of undefined

### ISSUE THREAD

**Issue by ngkarkeong** [smile-io/ember-cli-stripe#34]
It just simply failed to get the basic usage.

after installment, i try to set the publickey.
after i put
{{stripe-checkout
  image="/square-image.png"
  name="Demo Site"
  description="2 widgets ($20.00)"
  amount=2000
  onToken=(action "processStripeToken")
}} into a template.

it should get the result right?

i got an error massage Cannot read property 'getAttribute' of undefined.
what went wrong?

**Comment by vladucu** [comment]
@ngkarkeong sorry for the lack of answer....is this still a problem?

**Comment by ngkarkeong** [comment]
Nope, I don't remember I how I solve it. But I found a get around

**Comment by vladucu** [comment]
closing this, feel free to re-open if anyone else runs into this
